# https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=python

# application: bridgy-federated

service: default
env: flex
runtime: python
runtime_config:
  operating_system: ubuntu22
  # keep this in sync with the test job image's Python version in .circleci/config.yml!
  # change to "3.11" to use Cloud Profiler
  runtime_version: "3.12"

resources:
  cpu: 1
  memory_gb: 1

# run in default VPC for this project, same as router/hub
# https://cloud.google.com/appengine/docs/flexible/using-shared-vpc
# https://cloud.google.com/appengine/docs/flexible/reference/app-yaml#network_settings
#
# GAE Flex uses the VPC's network directly, *not* Serverless VPC Access
# https://docs.cloud.google.com/vpc/docs/serverless-vpc-access#supported_services
network:
  name: projects/bridgy-federated/global/networks/default

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.80

  # GAE Standard autoscaling settings:
  # max_instances: 100
  # min_idle_instances: 0
  # max_idle_instances: 1
  # # matches total number of gunicorn threads, across workers
  # max_concurrent_requests: 100
  # min_pending_latency: 1s
  # target_cpu_utilization: .8
  # target_throughput_utilization: .8

liveness_check:
  # default 300; lowering it speeds up deploy
  # https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=python#liveness_checks
  initial_delay_sec: 30

# https://cloud.google.com/appengine/docs/flexible/python/runtime#application_startup
# https://gunicorn.org/reference/settings/
entrypoint: gunicorn --workers 1 --threads 50 --timeout 60 -b :$PORT app:app

env_variables:
  DATASTORE_DB: us-single-region
  PDS_HOST: atproto.brid.gy
  PLC_HOST: plc.directory
  APPVIEW_HOST: api.bsky.app
  BGS_HOST: bsky.network
  MOD_SERVICE_HOST: mod.bsky.app
  MOD_SERVICE_DID: did:plc:ar7c4by46qjdydhdevvrndac
  MEMCACHE_HOST: '10.126.144.67'
  # ...or test against labeler.dholms.xyz / did:plc:vzxheqfwpbi3lxbgdh22js66
  SNAPCHAIN_HOST: crackle.farcaster.xyz

  # >- folds newlines into spaces, which arroba strips
  SUPPORTED_COLLECTIONS: >-
    app.bsky.actor.profile,
    app.bsky.feed.like,
    app.bsky.feed.post,
    app.bsky.feed.repost,
    app.bsky.graph.block,
    app.bsky.graph.follow,
    app.bsky.graph.listblock,
    chat.bsky.actor.declaration,
    community.lexicon.payments.webMonetization,
    site.standard.document,
    site.standard.publication

  # BLOB_REFETCH_DAYS: 30
  # this disables blob refetching
  # BLOB_REFETCH_TYPES: ''

  # set to enable read only mode (eg during planned maintenance)
  # https://github.com/snarfed/bridgy-fed/issues/2458
  # READ_ONLY: true

  # https://github.com/googleapis/python-ndb/blob/c55ec62b5153787404488b046c4bf6ffa02fee64/google/cloud/ndb/utils.py#L78-L81
  # NDB_DEBUG: true

  DISABLE_GETREPO: true
